In [1]:
import numpy as np

In [ ]:
# creating the array
my_array = np.array([4, 3, 2])
my_array

array([4, 3, 2])

In [ ]:
# multi dimensional array
my_nd_array = np.array([[1, 2, 34, 5], [3, 4, 2, 1]])
print("Array Dimensions: ", my_nd_array.shape)
print("Array: ", my_nd_array)
my_nd_array = np.array([[1, 2, 34, 5], [3, 4, 2, 1], [3, 4, 3, 2]])
print("Array Dimensions: ", my_nd_array.shape)
print("Array: ", my_nd_array)
my_nd_array = np.array(
    [
        [[1, 2, 34, 5], [3, 4, 2, 1], [3, 4, 3, 2]],
        [[1, 2, 34, 5], [3, 4, 2, 1], [3, 4, 3, 2]],
    ]
)
print("Array Dimensions: ", my_nd_array.shape)
print("Array: ", my_nd_array)
my_nd_array = np.array(
    [
        [
            [[1, 2, 34, 5], [3, 4, 2, 1], [3, 4, 3, 2]],
            [[1, 2, 34, 5], [3, 4, 2, 1], [3, 4, 3, 2]],
        ],
        [
            [[1, 2, 34, 5], [3, 4, 2, 1], [3, 4, 3, 2]],
            [[1, 2, 34, 5], [3, 4, 2, 1], [3, 4, 3, 2]],
        ],
    ]
)
print("Array Dimensions: ", my_nd_array.shape)
print("Array: ", my_nd_array)

Array Dimensions:  (2, 4)
Array:  [[ 1  2 34  5]
 [ 3  4  2  1]]
Array Dimensions:  (3, 4)
Array:  [[ 1  2 34  5]
 [ 3  4  2  1]
 [ 3  4  3  2]]
Array Dimensions:  (2, 3, 4)
Array:  [[[ 1  2 34  5]
  [ 3  4  2  1]
  [ 3  4  3  2]]

 [[ 1  2 34  5]
  [ 3  4  2  1]
  [ 3  4  3  2]]]
Array Dimensions:  (2, 2, 3, 4)
Array:  [[[[ 1  2 34  5]
   [ 3  4  2  1]
   [ 3  4  3  2]]

  [[ 1  2 34  5]
   [ 3  4  2  1]
   [ 3  4  3  2]]]


 [[[ 1  2 34  5]
   [ 3  4  2  1]
   [ 3  4  3  2]]

  [[ 1  2 34  5]
   [ 3  4  2  1]
   [ 3  4  3  2]]]]


In [ ]:
# specify minimum dimensions
my_array = np.array(
    [
        2,
        3,
        4,
        5,
    ],
    ndmin=2,
)
print("Array Dim: ", my_array.ndim, "\nArray Shape: ", my_array.shape)
my_array = np.array(
    [
        2,
        3,
        4,
        5,
    ],
    ndmin=3,
)
print("Array Dim: ", my_array.ndim, "\nArray Shape: ", my_array.shape)

Array Dim:  2 
Array Shape:  (1, 4)
Array Dim:  3 
Array Shape:  (1, 1, 4)


In [ ]:
# specify data types
my_array = np.array([3, 4, 2, 4, 4, 1], dtype=float)
print(my_array.dtype, my_array)
my_array = np.array([3, 4, 2, 4, 4, 1], dtype=str)
print(my_array.dtype, my_array)
my_array = np.array([3, 4, 2, 4, 4, 1], dtype=int)
print(my_array.dtype, my_array)
my_array = np.array([3, 4, 2, 4, 4, 1], dtype=bool)
print(my_array.dtype, my_array)
my_array = np.array([3, 4, 2, 4, 4, 1], dtype=complex)
print(my_array.dtype, my_array)

float64 [3. 4. 2. 4. 4. 1.]
<U1 ['3' '4' '2' '4' '4' '1']
int64 [3 4 2 4 4 1]
bool [ True  True  True  True  True  True]
complex128 [3.+0.j 4.+0.j 2.+0.j 4.+0.j 4.+0.j 1.+0.j]
