In [1]:
import numpy as np

In [ ]:
my_array = np.array([3, 4, 2])
my_array

array([3, 4, 2])

In [13]:
# zeros
my_array = np.zeros(4)
print(my_array)
# 2d
my_array = np.zeros((4, 2))
print(my_array)
# 3d
my_array = np.zeros((4, 2, 2))
print(my_array)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [19]:
# ones
my_array = np.ones(3)
print(my_array)
# 2d
my_array = np.ones((4, 3))
print(my_array)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
# arrange
my_array = np.arange(4)
print(my_array)
# 4 to 10
my_array = np.arange(4, 10)
print(my_array)
# 4 to 10 skippin 2 steps
my_array = np.arange(4, 10, 2)
print(my_array)

[0 1 2 3]
[4 5 6 7 8 9]
[4 6 8]


In [ ]:
# linspace
# start stop total
my_array = np.linspace(3, 6, 10)
my_array
my_array = np.linspace(3, 6, 10, endpoint=False)
my_array

array([3. , 3.3, 3.6, 3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7])

In [ ]:
# random.rand()
my_array = np.random.rand()
print(my_array)
# 2d
my_array = np.random.rand(2, 2)
print(my_array)

0.45950052957485477
[[0.50728519 0.2676424 ]
 [0.22369906 0.44628877]]


In [ ]:
# empty()
my_array = np.empty((2, 2))
print(my_array)
# Unlike numpy.zeros(), this function initializes the array with uninitialized values, which could be any random data left in memory, making it suitable for cases where immediate initialization is not required.

[[0.50728519 0.2676424 ]
 [0.22369906 0.44628877]]


In [ ]:
# full()
# t(otal, fill)
my_array = np.full(6, 4)
print(my_array)
# 2d
my_array = np.full((3, 2), 3)
print(my_array)
# 3d
my_array = np.full((3, 2, 2), 5)
print(my_array)

[4 4 4 4 4 4]
[[3 3]
 [3 3]
 [3 3]]
[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]
