In [1]:
import numpy as np

## Matrix Creation


In [38]:
# creating matrix
A = np.array([[2, 3, 4], [3, 9, -2], [3, -2, 1]])
print("A =\n", A)
B = np.array([[9, 5, -4], [1, 0, -7], [6, 7, 1]])
print("B =\n", B)

A =
 [[ 2  3  4]
 [ 3  9 -2]
 [ 3 -2  1]]
B =
 [[ 9  5 -4]
 [ 1  0 -7]
 [ 6  7  1]]


## Matrix Operations


In [ ]:
# add
C = A + B
print(C)

[[11  8  0]
 [ 4  9 -9]
 [ 9  5  2]]


In [12]:
# subtarct
C = A - B
print(C)

[[-7 -2  8]
 [ 2  9  5]
 [-3 -9  0]]


Matrix multiplication can be done using the @ operator or the np.dot() function. Unlike element-wise multiplication, matrix multiplication involves summing the products of rows and columns.


In [14]:
# multiplication
C = A @ B
print(C)

[[ 45  38 -25]
 [ 24   1 -77]
 [ 31  22   3]]


In [ ]:
# transpose
print("A:\n", A)
print("Transpose A:\n", A.T)
print("B:\n", B)
print("Transpose B:\n", B.T)

A:
 [[ 2  3  4]
 [ 3  9 -2]
 [ 3 -2  1]]
Transpose A:
 [[ 2  3  3]
 [ 3  9 -2]
 [ 4 -2  1]]
B:
 [[ 9  5 -4]
 [ 1  0 -7]
 [ 6  7  1]]
Transpose B:
 [[ 9  1  6]
 [ 5  0  7]
 [-4 -7  1]]


In [ ]:
# determinent
det_A = np.linalg.det(A)
print(f"det_A: {det_A:.2f}")

det_B = np.linalg.det(B)
print(f"det_B: {det_B:.2f} ")

det_A: -149.00
det_B: 198.00 


In [ ]:
# inverse
inv_A = np.linalg.inv(A)
inv_A = np.round(inv_A, 2)
print(inv_A)

[[-0.03  0.07  0.28]
 [ 0.06  0.07 -0.11]
 [ 0.22 -0.09 -0.06]]


In [ ]:
# eigenvalues and vectors

# vectors
print("Vectors")
eig_A = np.linalg.eig(A)
print(eig_A)
eig_B = np.linalg.eig(B)
eig_B

print("Values")
# values
eigv_A = np.linalg.eigvals(A)
print(eigv_A)
eigv_B = np.linalg.eigvals(B)
print(eigv_B)

Vectors
EigResult(eigenvalues=array([-3.01934114,  4.85512023, 10.16422091]), eigenvectors=array([[ 0.69554685, -0.72000756, -0.29453774],
       [-0.28346307,  0.20056558, -0.94920255],
       [-0.66019942, -0.66435123,  0.11073411]]))
Values
[-3.01934114  4.85512023 10.16422091]
[3.68517725+0.j        3.15741137+6.6150973j 3.15741137-6.6150973j]


In [ ]:
# solving linear systems

# 2 variables
A = np.array([[2, 3], [4, 5]])
B = np.array([2, 3])
solved = np.linalg.solve(A, B)
print(solved)

# 3 variables
A = np.array([[2, 3, 2], [4, 5, 0], [4, 3, 2]])
B = np.array([2, 0, 1])
solved = np.linalg.solve(A, B)
print(solved)

# 4 variables
A = np.array([[2, 3, 2, 4], [4, 5, 0, -6], [4, -3, 2, 0], [-1, 3, 2, 8]])
B = np.array([2, 0, 1, 5])
solved = np.linalg.solve(A, B)
print(solved)

[-0.5  1. ]
[-0.5  0.4  0.9]
[-4.625    0.4375  10.40625 -2.71875]


SVD is a factorization of a matrix into three matrices: U (the left singular vectors), S (the singular values) and V (the right singular vectors). It is useful in various applications, including signal processing and statistics.


In [55]:
# singular values decomposition
U, S, V = np.linalg.svd(A)

# U: left singular vectors
# S: singular values
# V: right singular vectors

print("U:\n", U)
print("S:\n", S)
print("V:\n", V)

U:
 [[ 0.34663805  0.52069087 -0.22404047 -0.74734794]
 [-0.56418298  0.7802268   0.08186365  0.25737531]
 [-0.06391392 -0.02488099 -0.96757811  0.24308136]
 [ 0.74662885  0.34569944  0.08304704  0.56226369]]
S:
 [11.2557886   7.73995838  5.51203271  0.13327652]
V:
 [[-0.22794852  0.05780382  0.18290197  0.95459157]
 [ 0.48024361  0.84948104  0.21744544  0.02157611]
 [-0.7391077   0.52413918 -0.40223692 -0.13116167]
 [-0.413673    0.01785526  0.87032741 -0.26661963]]


In [64]:
# norms and conditions

# L2 norm
norm_A = np.linalg.norm(A)
print("norm_A:", norm_A)
norm_B = np.linalg.norm(B)
print("norm_B:", norm_B)

# conditions
cond_A = np.linalg.cond(A)
print("cond_A: ", cond_A)
# # b is 1D, but cond() requires 2D, error
# cond_B = np.linalg.cond(B)
# print('cond_B: ', cond_B)

norm_A: 14.730919862656235
norm_B: 5.477225575051661
cond_A:  84.45440240294533
