In [9]:
import numpy as np

In [ ]:
my_array = np.array([4, 42, 32, 32, 32, 0])

## Copy


In [11]:
new_array = my_array.copy()
new_array

array([ 4, 42, 32, 32, 32,  0])

In [12]:
new_array[3] = 90
display(my_array)
display(new_array)

# does not change original

array([ 4, 42, 32, 32, 32,  0])

array([ 4, 42, 32, 90, 32,  0])

## View


In [13]:
view_array = my_array.view()
view_array

array([ 4, 42, 32, 32, 32,  0])

In [14]:
view_array[3] = 89
display(my_array)
display(view_array)
# changes the original array

array([ 4, 42, 32, 89, 32,  0])

array([ 4, 42, 32, 89, 32,  0])