In [13]:
import numpy as np

In [14]:
my_array = np.array([4, 42, 32, 32, 32, 0])

In [ ]:
my_array.reshape(3, 2)

array([[ 4, 42],
       [32, 32],
       [32,  0]])

In [ ]:
my_array = my_array.reshape(1, 3, 2)
my_array

array([[[ 4, 42],
        [32, 32],
        [32,  0]]])

In [22]:
# flatten
my_array = my_array.flatten()
my_array

array([ 4, 42, 32, 32, 32,  0])