In [1]:
import numpy as np

In [2]:
arr1 = np.array([3,4,3,2])
arr2 = np.array([2,7,2,1])

display(arr1)
display(arr2)

array([3, 4, 3, 2])

array([2, 7, 2, 1])

## Concatenate

In [5]:
# concat
concatenated_array = np.concatenate((arr1, arr2))
display(concatenated_array)
concatenated_array = np.concatenate((arr2, arr1))
display(concatenated_array)

array([3, 4, 3, 2, 2, 7, 2, 1])

array([2, 7, 2, 1, 3, 4, 3, 2])

In [6]:
# 2d arrays
array1 = np.array([[3,4,3,2],[4,3,7,6]])
array2 = np.array([[3,7,8,2],[43,22,11,5]])

concat_2d_array = np.concatenate((array1, array2))
display(concat_2d_array)

array([[ 3,  4,  3,  2],
       [ 4,  3,  7,  6],
       [ 3,  7,  8,  2],
       [43, 22, 11,  5]])

## stack

In [11]:
# vertically
v_stacked_array = np.stack((arr1, arr2), axis=1)
display(v_stacked_array)
# horizontally
h_stacked_array = np.stack((arr1, arr2), axis=0)
display(h_stacked_array)

array([[3, 2],
       [4, 7],
       [3, 2],
       [2, 1]])

array([[3, 4, 3, 2],
       [2, 7, 2, 1]])

In [ ]:
# hstack, along rows
h_stacked = np.hstack((arr1, arr2))
display(h_stacked)

array([3, 4, 3, 2, 2, 7, 2, 1])

In [ ]:
# vstack, along columns
v_stacked = np.vstack((arr1, arr2))
display(v_stacked)

array([[3, 4, 3, 2],
       [2, 7, 2, 1]])

In [15]:
# dstack, along depth
d_stacked = np.dstack((arr1, arr2))
display(d_stacked)

array([[[3, 2],
        [4, 7],
        [3, 2],
        [2, 1]]])