In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,2,1,6,5,6,56,45])

In [9]:
# split arrays into parts
split1 = np.array_split(arr, 2) # two parts
display(split1)
split2 = np.array_split(arr, 3) # 3 parts
display(split2)
split3 = np.array_split(arr, 5) # 4 parts
display(split3)

[array([4, 3, 2, 1, 6]), array([ 5,  6, 56, 45])]

[array([4, 3, 2]), array([1, 6, 5]), array([ 6, 56, 45])]

[array([4, 3]), array([2, 1]), array([6, 5]), array([ 6, 56]), array([45])]

In [10]:
display(split3[0])
display(split3[1])
display(split3[2])
display(split3[3])
display(split3[4])

array([4, 3])

array([2, 1])

array([6, 5])

array([ 6, 56])

array([45])

In [17]:
# 2d array split
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
split_2d = np.array_split(arr_2d, 3)

In [18]:
display(split_2d[0])
display(split_2d[1])
display(split_2d[2])

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8,  9],
       [10, 11, 12]])

array([[13, 14, 15],
       [16, 17, 18]])

In [23]:
# split along axis=1
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
split_axis_1 = np.array_split(arr, 2, axis=1)
display(split_axis_1[0])
display(split_axis_1[1])
# split along axis=0
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
split_axis_2 = np.array_split(arr, 2, axis=0)
display(split_axis_2[0])
display(split_axis_2[1])


array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14],
       [16, 17]])

array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [31]:
# hsplit, split along columns
h_split = np.hsplit(arr, 3)
display(h_split[0])
display(h_split[1])
display(h_split[2])
# vsplit, split along rows
v_split = np.vsplit(arr, 3)
display(v_split[0])
display(v_split[1])
display(v_split[2])
# dsplit, split along depth
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]]])
d_split = np.dsplit(arr3, 3)
display(d_split[0])
display(d_split[1])
display(d_split[2])

array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]])

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])

array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8,  9],
       [10, 11, 12]])

array([[13, 14, 15],
       [16, 17, 18]])

array([[[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]])

array([[[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]])

array([[[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]])