In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

In [8]:
# where
item1 = np.where(arr==4)
display(item1)
evens = np.where(arr%2==0)
display(evens)
odds = np.where(arr%2==1)
odds

(array([1]), array([0]))

(array([0, 1, 1, 2, 3, 3, 4, 5, 5]), array([1, 0, 2, 1, 0, 2, 1, 0, 2]))

(array([0, 0, 1, 2, 2, 3, 4, 4, 5]), array([0, 2, 1, 0, 2, 1, 0, 2, 1]))

In [16]:
# searchsorted
arr = np.array([3,2,1,5,6,7])
search = np.searchsorted(arr, 7)
display(search)
search = np.searchsorted(arr, 5, side='right')
display(search)
search = np.searchsorted(arr, [0,4])
display(search)

np.int64(5)

np.int64(4)

array([0, 3])