In [1]:
import numpy as np

In [8]:
arr_1d = np.array([3,2,1,5,6,7])
arr_2d = np.array([[3,2,1,5,6,7], [6,5,4,5,9,8]])
bool_arr = np.array([True, False, True])
display(arr_1d)
display(arr_2d)

array([3, 2, 1, 5, 6, 7])

array([[3, 2, 1, 5, 6, 7],
       [6, 5, 4, 5, 9, 8]])

In [9]:
sorted_1d = np.sort(arr_1d)
display(sorted_1d)
sorted_2d = np.sort(arr_2d)
display(sorted_2d)
sorted_bool_arr = np.sort(bool_arr)
display(sorted_bool_arr)

array([1, 2, 3, 5, 6, 7])

array([[1, 2, 3, 5, 6, 7],
       [4, 5, 5, 6, 8, 9]])

array([False,  True,  True])