In [1]:
import numpy as np

In [6]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
display(arr[x]) # only considers True places in x (0 and 1)

arr = np.array([41, 42, 43, 44])
x = [True, False, False, False]
display(arr[x]) # only considers True places in x (1)

array([41, 43])

array([41])

In [14]:
# create filter
arr = np.array([34,56,78,54,23,45,67,89])
arr_filter = []

for item in arr:
    if item > 60:
        arr_filter.append(True)
    else:
        arr_filter.append(False)
        
new_filter_array = arr[arr_filter]
display(arr)
display(arr_filter)
display(new_filter_array)

array([34, 56, 78, 54, 23, 45, 67, 89])

[False, False, True, False, False, False, True, True]

array([78, 67, 89])

In [15]:
# create filter
arr = np.array([34,56,78,54,23,45,67,89])
arr_filter = []

for item in arr:
    if item%2 == 0:
        arr_filter.append(True)
    else:
        arr_filter.append(False)
        
new_filter_array = arr[arr_filter]
display(arr)
display(arr_filter)
display(new_filter_array)

array([34, 56, 78, 54, 23, 45, 67, 89])

[True, True, True, True, False, False, False, False]

array([34, 56, 78, 54])