In [1]:
import numpy as np

In [4]:
my_array = np.random.randint(144)
display(my_array)

20

In [ ]:
my_array = np.random.rand()
display(my_array)
my_array = np.random.rand(8)
display(my_array)

0.9407154865146582

array([0.06482028, 0.94450769, 0.06784323, 0.91323108, 0.28387507,
       0.84683141, 0.60062179, 0.10520068])

In [8]:
# specific size
my_array = np.random.randint(100, size=(8))
display(my_array)
my_array = np.random.randint(100,size=(3,5))
display(my_array)

array([79, 19, 77, 13, 13,  2, 11, 20], dtype=int32)

array([[47, 81, 12,  7, 71],
       [66, 97, 48,  5, 35],
       [53, 53, 61, 12,  3]], dtype=int32)

In [13]:
# specific choice
my_array = np.random.choice([4.,4,42,25,75])
display(my_array)
my_array = np.random.choice([4.,4,42,25,75], size=(3,4))
display(my_array)

np.float64(4.0)

array([[25.,  4., 75.,  4.],
       [75., 75.,  4.,  4.],
       [25., 75., 42.,  4.]])