Data Distribution is a list of all possible values, and how often each value occurs.

In [1]:
import numpy as np

In [ ]:
x = np.random.choice([3,5,4,7], p=[0.1, 0.6, 0.1, 0.2], size=(100))
print(x)
print()

[5 5 3 5 7 3 5 5 5 7 5 3 5 5 5 7 3 5 5 5 3 7 5 5 7 5 5 7 3 5 5 7 5 3 5 3 5
 5 4 5 7 5 3 5 5 5 5 5 5 5 5 3 7 3 5 5 5 7 5 5 3 5 4 5 3 3 4 4 7 3 4 7 5 4
 7 5 5 5 5 5 7 5 3 4 5 5 5 4 5 7 5 7 5 5 5 3 5 7 5 5]


In [9]:
fives = []
threes = []
sevens = []
for i in x:
    if i == 5:
        fives.append(i)
    if i==7:
        sevens.append(i)
    if i==3:
        threes.append(i)    
print(len(fives))
print(len(sevens))
print(len(threes))

58
17
17


In [18]:
x = np.random.choice([3,5,4,7], p=[0.1, 0.6, 0.1, 0.2], size=(3,5))
print(x)
print()

[[7 3 5 5 5]
 [5 7 5 7 5]
 [5 4 5 4 7]]

