In [1]:
import numpy as np

In [20]:
# shuffle
my_array = np.array([4,5,2,3,52,87,54])
display(my_array)
np.random.shuffle(my_array)
display(my_array)
# makes changes in the original array

array([ 4,  5,  2,  3, 52, 87, 54])

array([ 3,  2, 87,  5,  4, 54, 52])

In [21]:
# permutation
print(np.random.permutation(my_array))
# does not change original array

[ 3  4  5 54 52  2 87]
